### ISSUE TITLE
Tag anywhere change from Tiny's mini mode keeps draining crystals

### ISSUE THREAD

**Issue by Killklli** [2dos/DK64-Randomizer#103]
When you swap from tiny while she is shrunk it does not seem to cancel the shrunk animation/drain/music.

**Comment by theballaam96** [comment]
Pressing Z + C-Left fixes this, it's just visually the kong remains at normal scale. Implement auto-detransform into Tag Anywhere

**Comment by theballaam96** [comment]
Example of this behaviour (but with Tag Barrel Storage instead of Tag Anywhere) can be found in the DK64 101% TAS: https://www.youtube.com/watch?v=mPleO8JH4g8&t=2h7m47s
