### ISSUE TITLE
Make Llama Temple kong underwater gate open instantly with removed cutscenes

### ISSUE THREAD

**Issue by theballaam96** [2dos/DK64-Randomizer#1098]
https://discord.com/channels/463917049782075395/559837167430664203/1045531225760206868

**Comment by theballaam96** [comment]
Thanksgiving report

**Comment by AlmostSeagull** [comment]
Gate's sound now won't stop (at least on N64 and I think on Wii U VC too during Draqueus's run from that charity event) https://clips.twitch.tv/TenuousSmokySowTakeNRG-_RBl2J-CqeplakHb
