### ISSUE TITLE
Support older versions of the generator

### ISSUE THREAD

**Issue by theballaam96** [2dos/DK64-Randomizer#1251]
Killi: If we shift the writing part of the patching process to a webworker, we can set it to load a particular SHA version of the site for the patching and remove the limitations on matching hash versions by using that particular version of the site for patching
We would still need to keep a hash of that site version and the hash of the patch file to make sure they match exactly so people can't make changes underneath it

**Comment by Killklli** [comment]
https://stackoverflow.com/questions/60255670/is-there-a-way-to-include-the-git-hash-in-a-github-pages-site
