### ISSUE TITLE
Move Randomizer dropdown doesn't update when clicking "Select All" or "Reset" in the  Item Randomizer list selector

### ISSUE THREAD

**Issue by AlmostSeagull** [2dos/DK64-Randomizer#1304]
In the Move Randomizer "Unlock All Moves" is greyed out and I don't know how to ungrey it, and at this point I think it's a bug. If I figure out how to ungrey it, I'll let y'all know. 
Edit: Changing title to: Move Randomizer dropdown doesn't update when disabling Item Randomizer
Edit: Changing title to: Move Randomizer dropdown doesn't update when clicking "Select All" or "Reset" in the Item Randomizer list selector

**Comment by AlmostSeagull** [comment]
Figured out how to workaround this: 
Enable Item Randomizer
Select something and make sure shops is not selected
And that's it. Don't even need to disable Item Randomizer, that's optional.

**Comment by theballaam96** [comment]
Closing as resolved

**Comment by AlmostSeagull** [comment]
Not quite resolved, but I should specify: The reset button and the Select All button on the Item Rando selector do not update (disable/enable) the items in the Move Rando dropdown.
