### ISSUE TITLE
Impossible Beat K. Rool seed via character lockout on 2.0 release.

### ISSUE THREAD

**Issue by retrobenny** [2dos/DK64-Randomizer#1515]
I need Chunky to fight K. Rool so, Chunky is in Jungle Japes Mini-Monkey cage, but Tiny is in a shop for Chunky to purchase meaning no way beyond King Kutout to obtain Chunky or Tiny which I would expect not to be in logic despite the patch that prevented smuggling Kongs from Kutout before being removed. (or it now fails to prevent smuggling Kongs?)
If that is in glitched logic then I think it should have a setting toggle for it.

Here is my settings string in a txt and spoiler log file (zipped) attached.
[DK64r 133769 Settings.txt](https://github.com/2dos/DK64-Randomizer/files/11973766/DK64r.133769.Settings.txt)
[133769-spoilerlog.zip](https://github.com/2dos/DK64-Randomizer/files/11973771/133769-spoilerlog.zip)

**Comment by theballaam96** [comment]
It's an error in logic, but not in the way you're thinking.
It thinks you can get Chunky with Lanky + Skew. However, since you have Free Trade Agreement off, you can't grab them.
Seems like the logic file for that GB doesn't correctly account for FTA:
```py
LocationLogic(Locations.JapesTinyStump, lambda l: (l.mini and l.istiny) or l.phasewalk or l.CanSkew(True)),
```

We'll get to fixing this asap.

Thanks,
DK64R Dev Team

**Comment by retrobenny** [comment]
Funny thing is I now tend to get that item check just by walking off the back to do a basic slope slide that clips the top of it enough to usually collect the item inside without needing mini-monkey, no skew required.

**Comment by theballaam96** [comment]
Right, that's a minor bug with the new collision system we've worked on. As such, it's not in logic. Phasewalking/mini/skew is the only methods in logic
