### ISSUE TITLE
Why didn't I don't like mobile plafirst I tried to download it for mobile but not working

### ISSUE THREAD

**Issue by Loganlanner1** [2dos/DK64-Randomizer#1551]

**Comment by theballaam96** [comment]
Please can you be more descriptive? You've made a GH issue before. We **can't** address issues if we don't get sufficient information

**Comment by theballaam96** [comment]
Closing from insufficient information. If/when you create another bug report, **PLEASE** include information that will help us diagnose and come up with a solution or response to this issue. In the case of this issue:
> - What are you trying to download for mobile?
> - What emulator are you using (we don't support mobile emulators for various reasons, but this is crucial information to have)?
> - How is it not working? Are you getting a crash? Is your emulator reporting an error upon trying to open the ROM?
> - What kind of phone do you have?
> - If it's an error with the site, what browser are you using?

We **can't** address issues when we don't have any specific information on what is happening. It's also recommended that if you create a GitHub issue, you keep an eye on responses and help us out with your specific case for when we ask questions.

**Comment by Loganlanner1** [comment]
Galaxy A14 l
