### ISSUE TITLE
"Faster Checks" setting links to out-of-date documentation

### ISSUE THREAD

**Issue by tiduslaugh** [2dos/DK64-Randomizer#1680]
**Describe the bug**
The "Faster Checks" option under the "Overworld" tab of the randomizer page links to the wrong anchor on the [Feature Explanations](https://github.com/2dos/DK64-Randomizer/wiki/Feature-Explanations) page--it links to the `#faster-checks` anchor which was replaced by the `#fast-golden-bananas` anchor in commit e3bdd68427eee988d7622c7bab9f1666ea3a43e7.

**To Reproduce**
1. Go to https://dk64randomizer.com/randomizer.html
2. Click on the Overworld tab
3. Click on the external link icon next to "Faster Checks"
4. Verify that you are sent to https://github.com/2dos/DK64-Randomizer/wiki/Feature-Explanations#faster-checks (which does not exist so you just go to the top of the page)

**Expected behavior**
Expect to be sent to the `#fast-golden-bananas` anchor. (It might also help to rename the option so that it matches the heading you are sent to.)

**Comment by theballaam96** [comment]
Good catch, we will change this when we get the time

**Comment by theballaam96** [comment]
Multiselector on dev site essentially fixed this as there's no longer a link from the site to the wiki on this topic. Closing as "completed"
