### ISSUE TITLE
Fungi Forest Launching Barrels 

### ISSUE THREAD

**Issue by Ghostface211008** [2dos/DK64-Randomizer#1948]
it's not working right. the first automatic barrels are still and the 3rd automatic barrel automatically misses. I also can't activate those cannons in the Giant Mushrooms.

**Comment by theballaam96** [comment]
Could you elaborate further? Are you talking about the barrel blast course in Fungi Forest? If so, provide a BPS to your seed: https://dk64randomizer.com/bps_maker

As for the GM cannons, shooting the 5 switches inside the giant mushroom spawns the cannons inside

**Comment by Ghostface211008** [comment]
sent it via email because this site doesn't support it. did you get it?

**Comment by Ghostface211008** [comment]
hello?

**Comment by theballaam96** [comment]
I did not receive the email you reference. Just upload the BPS to Google drive, and share the link (make sure to set it to anyone with the link can view)

**Comment by Ghostface211008** [comment]
Ok, I will do that.

**Comment by Ghostface211008** [comment]
https://drive.google.com/file/d/1bxhf3udYI2qXlff-6nNf888dwb3ArQ5g/view?usp=drive_link

**Comment by Ghostface211008** [comment]
also, moves were acting up. the were out of sync and to get starting moves for each Kong, I had to go back to the original location to get it.

**Comment by theballaam96** [comment]
What platform/emulator were you using?

**Comment by Ghostface211008** [comment]
Project64.

**Comment by Ghostface211008** [comment]
have you found the issue?

**Comment by Ghostface211008** [comment]
That was a week apart from my prior commitment. I'd hardly call that
"frequent".

**Comment by 2dos** [comment]
Blocking user due to rudeness and closing this issue.
