### ISSUE TITLE
Colored Bananas on DK Isles? (Dropdown Menu Option) + All Keys Obtained not working

### ISSUE THREAD

**Issue by Lemmy-15** [2dos/DK64-Randomizer#2029]
If I set the "colored bananas" dropdown to On (Inc. Isles), the seed generation just straight-up fails. The fairy explodes (which I thought was really funny) every time.
And, the other day when I did a randomizer where the objective was "all keys," when I got all 8 keys (the menu said so), the credits didn't appear. I was just tossed right back into Frantic Factory. Favorite level? Maybe, but just not what was supposed to happen.
Lastly, the Plandomizer doesn't allow you to specify Level Bosses as K. Rool phases. I just thought it'd be fun to make a boss rush out of the final fight. I'd also like to be able to specify which level each boss appears in, so when I set "Castle Boss Defeated" to Key 7 in my Plandomizer, I don't run into Puftoss.
Add more Kong Model Options! It's so funny.

Just really wanted to "report" the first two things. You guys are doing a fantastic Job, thanks for making my favorite game even more ridiculous.

**Comment by pbeierle22** [comment]
1. In this early state of 4.0, it's unlikely that a single toggle is breaking things and it's instead a combination of a settings. We'll need a settings string to better debug this.
2. The all keys bug is a known issue. A [.bps file](https://dev.dk64randomizer.com/bps_maker.html) might assist in debugging this. 
3. Plandomizer is fairly limited in scope at the moment and tends to lag behind new settings for some time. It'll get there.
Thanks for reporting your issues, happy donkin

**Comment by theballaam96** [comment]
Number 2 has been fixed. Not sure if number 1 has (would need the specific settings string to verify that).
