### ISSUE TITLE
Sometimes get a "Hash Mismatch" Error when generating a seed

### ISSUE THREAD

**Issue by Cfox7** [2dos/DK64-Randomizer#385]
Have seen this happen a few times seemingly randomly. Not sure what is causing it

![image](https://user-images.githubusercontent.com/16396700/172030365-750c0f38-f59f-4551-b27f-7f1264bc7832.png)

**Comment by Killklli** [comment]
That's the stack itself checking for if code is out of sync so people cant modify the live site and give out patch files where they got stuff changed.
They may have hit it while we were redeploying
