### ISSUE TITLE
Kasplat Location Randomizer

### ISSUE THREAD

**Issue by theballaam96** [2dos/DK64-Randomizer#435]
Current Status:
22-JUN-2022: Needs separate writer file. Needs logic for each location. Needs to append kasplats to item list. List of locations needs to be gone through to make sure there's no bad locations, and to add new better ones (considering that certain restrictions that were a thing in LUA days aren't a problem anymore)

**Comment by cjohnson57** [comment]
Need to create the system to dynamically add/remove kasplats from different regions in logic
