### ISSUE TITLE
Minecarts can be inaccessible if their exits lead to themselves with loading zones randomized.

### ISSUE THREAD

**Issue by retrobenny** [2dos/DK64-Randomizer#484]
In a spoiler log for _seed 216464_ it says in shuffled exits;

"Jungle Japes Minecart to Main": "Jungle Japes Minecart",

And there is no other entrance/exit instance listed that leads to the Jungle Japes Minecart.
I had been looking everywhere and never ran into it and now have all other 200 GBs.
Edit; Forgot to mention I set it to decoupled loading zones for maximum fun.

**Comment by theballaam96** [comment]
Thank you for filing this bug report. I will pass it on to the logic guys within the dev team who will get this fixed for V1.1. Could you include a copy of `spoiler_log.json` please?

**Comment by retrobenny** [comment]
[216464-spoilerlog.zip](https://github.com/2dos/DK64-Randomizer/files/8983621/216464-spoilerlog.zip)
