### ISSUE TITLE
Kongs can purchase moves from other kongs

### ISSUE THREAD

**Issue by theballaam96** [2dos/DK64-Randomizer#501]
Needs logic to treat move purchasing as locked to the kong it's assigned to (rather than treating it as a shared move)

**Comment by cjohnson57** [comment]
Need to correct logic so that moves are still only for specific kongs

**Comment by cjohnson57** [comment]
Logic has been corrected

**Comment by cjohnson57** [comment]
Should have probably linked the PR: #525
