### ISSUE TITLE
Fix Squawks w/ Spotlight

### ISSUE THREAD

**Issue by theballaam96** [2dos/DK64-Randomizer#746]

**Comment by AlmostSeagull** [comment]
Progress: 
Almost have it replicating its vanilla behavior with 4 or so coding mistakes currently: 
1. Its flies very slowly while its speed seems fine
2. It's not at the correct height 
3. It's not at the correct height
4. It's not staying far enough away (this is a plus, but let's first replicate its vanilla behavior lol)
