### ISSUE TITLE
Change Win Condition

### ISSUE THREAD

**Issue by theballaam96** [2dos/DK64-Randomizer#790]
Ideas from Keipers stream:
- Get Key 8 (Alternative to "Skip K. Rool"/"Skip Bosses" since you only need Keys 6/7 and the GBs (and other helm reqs)
- All Fairies Pictured (Fairy location rando req)
- All blueprints
- All Banana Medals
- Pokemon Snap (Snap every enemy)

## Key 8
- [x] Base Hack
- [x] Logic

## All Fairies
- [x] Base Hack
- [x] Logic
- [x] Fairy amount selector

## All Blueprints
- [x] Base Hack
- [x] Logic
- [x] Blueprint amount selector

## All Medals
- [x] Base Hack
- [x] Logic
- [x] Medal amount selector

## Pokemon Snap
- [x] Base Hack
- [x] Logic
- [x] In-Game tracker
- [x] Set Enemies enabled bitfield

**Comment by theballaam96** [comment]
Needs logic, need to add pkmn snap goal

**Comment by AlmostSeagull** [comment]
Win condition idea: All moves
