### ISSUE TITLE
Super Slam shouldn't be hinted as a woth hint

### ISSUE THREAD

**Issue by theballaam96** [2dos/DK64-Randomizer#904]
Super Slam is currently woth all the time, but is misleading a little (implying that you can only get super slam from one location). This goes against the trend of randomizers (Notably ZOOTR) with regard to woth hints.

As such, the feedback/suggestions regarding slam woth is that it should only be hinted as a "slam is in this shop" hint rather than a woth hint if only SSS is required.

**Comment by pbeierle22** [comment]
We should be able to calculate if a slam locks another slam, which would make the first slam logically forced. In that case it should definitely be hinted, otherwise make it an unhintable woth item (like Kongs are).
