### ISSUE TITLE
Light-Arrows like hint

### ISSUE THREAD

**Issue by theballaam96** [2dos/DK64-Randomizer#929]
Ballaam — Yesterday at 6:28 PM
Okay, idea
It's bold
But I think it could be amazing
Upon picking up whatever is in the key 8 spot, it fades into the K. Rool button cutscene
During the cutscene, we have K. Rool say the hint in somewhat the same tone as that text 2dos posted

**Comment by AlmostSeagull** [comment]
Sounds cool! What is the text 2dos posted, though, if that's alright to ask?

**Comment by theballaam96** [comment]
> Sounds cool! What is the text 2dos posted, though, if that's alright to ask?

Was just an example of light arrows text with ZOOTR
